"""trailer_type

Revision ID: 58200740da75
Revises: e6916fb7399d
Create Date: 2023-09-19 20:25:37.980634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "58200740da75"
down_revision: Union[str, None] = "e6916fb7399d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transport", sa.Column("trailer_type", sa.String(), nullable=True))
    op.drop_constraint("transport_brand_model_type_key", "transport", type_="unique")
    op.create_unique_constraint(
        None, "transport", ["brand", "model", "type", "trailer_type"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "transport_brand_model_type_trailer_type_key", "transport", type_="unique"
    )
    op.create_unique_constraint(
        "transport_brand_model_type_key", "transport", ["brand", "model", "type"]
    )
    op.drop_column("transport", "trailer_type")
    # ### end Alembic commands ###
