"""added tg chat id

Revision ID: 4c1d6e67b91a
Revises: 
Create Date: 2023-09-29 07:58:21.194458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4c1d6e67b91a"
down_revision: Union[str, None] = "58200740da75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("master", sa.Column("tg_chat_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_master_tg_chat_id"), "master", ["tg_chat_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_master_tg_chat_id"), table_name="master")
    op.drop_column("master", "tg_chat_id")
    # ### end Alembic commands ###
