"""added order_history and clone_order_id

Revision ID: 4f7f82c173d1
Revises: 4c1d6e67b91a
Create Date: 2023-10-14 08:26:10.033209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4f7f82c173d1"
down_revision: Union[str, None] = "4c1d6e67b91a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("master_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["master_id"],
            ["master.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_order_history_id"), "order_history", ["id"], unique=False)
    op.create_index(
        op.f("ix_order_history_master_id"), "order_history", ["master_id"], unique=False
    )
    op.add_column("order", sa.Column("clone_order_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_order_clone_order_id"), "order", ["clone_order_id"], unique=False
    )
    op.create_foreign_key(
        "order_clone_order_id_fkey", "order", "order", ["clone_order_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("order_clone_order_id_fkey", "order", type_="foreignkey")
    op.drop_index(op.f("ix_order_clone_order_id"), table_name="order")
    op.drop_column("order", "clone_order_id")
    op.drop_index(op.f("ix_order_history_master_id"), table_name="order_history")
    op.drop_index(op.f("ix_order_history_id"), table_name="order_history")
    op.drop_table("order_history")
    # ### end Alembic commands ###
